// 카드 위젯 아이콘 허용셋 — 저장 이름(kebab-case) → lucide 컴포넌트 + 한글 라벨.
//
// ⚠️ 이 목록은 backend `app/widgets/registry.py` 의 `_CARD_ICONS` 와 **쌍**이다.
// 백엔드는 enum 으로 저장을 거부하고, 여기는 실제로 그릴 수 있는 것을 정한다.
// 한쪽에만 추가하면: 백엔드만 → 저장은 되는데 화면에 안 그려짐(조용히 무시),
// 프론트만 → 저장이 422 로 거부됨. **반드시 함께** 고칠 것.
// 목록 동기화는 `tests/test_widgets_card.py` 가 개수로 잡아 준다.
//
// 임의의 lucide 이름(3,900여 개)을 다 열지 않는 이유: (1) 정적 import 해야 번들에
// 들어가고, (2) 고를 수 없을 만큼 많으면 피커가 건초더미가 되며, (3) PPTX/DOCX
// export 가 같은 셋만 래스터화한다. 대신 **전자제품 R&D** 도메인에 맞춰 넓게 잡았다.
import {
  Activity, AirVent, AlertCircle, Antenna, Anvil, Aperture, Archive, Atom, AudioWaveform,
  Award, BadgeCheck, Ban, Banknote, Barcode, Battery, BatteryCharging, BatteryFull, BatteryLow,
  BatteryMedium, BatteryWarning, Beaker, Bell, Binary, Blocks, Bluetooth, BluetoothConnected,
  BluetoothSearching, Bolt, Book, BookOpen, BookmarkCheck, Boxes, Braces, Briefcase, Bug,
  BugPlay, Building2, Cable, Calculator, Calendar, CalendarClock, Camera, ChartArea, ChartBar,
  ChartCandlestick, ChartColumn, ChartGantt, ChartLine, ChartNetwork, ChartPie, ChartScatter,
  ChartSpline, CheckCheck, CircleCheck, CircleDot, CircleHelp, CircleSlash, CircuitBoard,
  ClipboardCheck, ClipboardList, Clock, Cloud, CloudDownload, CloudUpload, Code, Cog, Coins,
  Component, Construction, Contact, Container, Cpu, Database, DatabaseZap, Disc, Drill,
  Droplet, EthernetPort, Eye, Factory, Fan, FileCheck, FileCode, FilePlus, FileSearch,
  FileText, Files, Filter, Fingerprint, Flag, Flame, Flashlight, FlaskConical, FlaskRound,
  Focus, Folder, FolderGit, FolderOpen, Forklift, Fuel, Gauge, GaugeCircle, GitBranch,
  GitCommitHorizontal, GitMerge, GitPullRequest, Globe, Grid2x2, Hammer, Handshake, HardDrive,
  HardHat, Headphones, Hexagon, Highlighter, History, IdCard, Info, Joystick, Kanban, Keyboard,
  Lamp, Landmark, Languages, Laptop, Layers, LayoutDashboard, Leaf, Lightbulb, Link,
  ListChecks, ListOrdered, ListTodo, Lock, Magnet, Mail, MapPin, Medal, MemoryStick, Mic,
  Microchip, Microscope, Microwave, Milestone, Monitor, MonitorSmartphone, Mouse, Network, Nfc,
  NotebookPen, OctagonAlert, Orbit, Package, PackageCheck, PackageOpen, PackageSearch,
  Paperclip, PenTool, Percent, Pin, Plug, PlugZap, Power, PowerOff, Presentation, Printer,
  Projector, Puzzle, Quote, Radar, Radiation, Radio, RadioReceiver, RadioTower, Receipt,
  Recycle, RefreshCw, Refrigerator, Router, Rss, Ruler, RulerDimensionLine, Satellite,
  SatelliteDish, Scale, Scan, ScanBarcode, ScanEye, ScanLine, ScanQrCode, ScanSearch,
  ScrollText, Search, Server, ServerCog, Settings, Share2, Shield, ShieldAlert, ShieldCheck,
  ShieldOff, ShieldX, ShoppingCart, Sigma, Signal, SignalHigh, SignalLow, SignalZero,
  Signature, Smartphone, SmartphoneCharging, SmartphoneNfc, Snowflake, Sparkles, Speaker,
  Spline, Stamp, Star, StickyNote, Store, Syringe, Table, TableOfContents, Tablet,
  TabletSmartphone, Target, Terminal, TestTube, TestTubes, Thermometer, ThermometerSnowflake,
  ThermometerSun, ThumbsDown, ThumbsUp, Timer, TimerReset, Trash2, TrendingDown, TrendingUp,
  TrendingUpDown, TriangleAlert, TriangleDashed, Trophy, Truck, TruckElectric, Tv, User,
  UserCheck, UserPlus, Users, UsersRound, Volume2, Wallet, Warehouse, WashingMachine, Watch,
  Waves, Waypoints, Webcam, Weight, Wifi, WifiHigh, WifiLow, WifiOff, Wind, Workflow, Wrench,
  Zap, ZapOff
} from 'lucide-react'

/**
 * 아이콘 정의. `name` 이 저장값, `label` 이 피커·검색에 쓰는 한글 이름,
 * `group` 은 피커의 묶음. 순서 = 피커 노출 순서.
 * `keywords` 는 한글 라벨로는 안 잡히는 검색어 보강(선택).
 */
export const CARD_ICON_DEFS = [
  // ── 반도체 · 회로 ────────────────────────────────────────────────
  { name: 'cpu', label: '반도체', group: '반도체·회로', Cmp: Cpu, keywords: '칩 프로세서 소자' },
  { name: 'microchip', label: '칩', group: '반도체·회로', Cmp: Microchip },
  { name: 'circuit-board', label: '기판', group: '반도체·회로', Cmp: CircuitBoard, keywords: 'pcb 회로' },
  { name: 'component', label: '부품', group: '반도체·회로', Cmp: Component },
  { name: 'memory', label: '메모리', group: '반도체·회로', Cmp: MemoryStick },
  { name: 'binary', label: '이진데이터', group: '반도체·회로', Cmp: Binary, keywords: '디지털 신호' },
  { name: 'puzzle', label: '모듈', group: '반도체·회로', Cmp: Puzzle, keywords: '조합' },
  { name: 'atom', label: '소재', group: '반도체·회로', Cmp: Atom, keywords: '원자 물성 재료' },
  { name: 'blocks', label: '적층', group: '반도체·회로', Cmp: Blocks, keywords: '스택 다층' },
  { name: 'hexagon', label: '셀', group: '반도체·회로', Cmp: Hexagon, keywords: '격자 구조' },
  { name: 'grid', label: '배열', group: '반도체·회로', Cmp: Grid2x2, keywords: '매트릭스 어레이' },
  { name: 'spline', label: '특성곡선', group: '반도체·회로', Cmp: Spline, keywords: '커브' },
  { name: 'waypoints', label: '경로', group: '반도체·회로', Cmp: Waypoints, keywords: '라우팅 배선' },

  // ── 전원 · 전력 ──────────────────────────────────────────────────
  { name: 'battery', label: '배터리', group: '전원·전력', Cmp: Battery },
  { name: 'battery-charging', label: '충전', group: '전원·전력', Cmp: BatteryCharging },
  { name: 'battery-warning', label: '배터리 경고', group: '전원·전력', Cmp: BatteryWarning },
  { name: 'power', label: '전원', group: '전원·전력', Cmp: Power },
  { name: 'plug', label: '플러그', group: '전원·전력', Cmp: Plug },
  { name: 'plug-zap', label: '급속충전', group: '전원·전력', Cmp: PlugZap },
  { name: 'zap', label: '전기', group: '전원·전력', Cmp: Zap, keywords: '번개 순간' },
  { name: 'bolt', label: '전압', group: '전원·전력', Cmp: Bolt },
  { name: 'battery-full', label: '만충', group: '전원·전력', Cmp: BatteryFull, keywords: '완충' },
  { name: 'battery-medium', label: '잔량', group: '전원·전력', Cmp: BatteryMedium, keywords: '중간' },
  { name: 'battery-low', label: '저전압', group: '전원·전력', Cmp: BatteryLow, keywords: '방전 부족' },
  { name: 'power-off', label: '전원차단', group: '전원·전력', Cmp: PowerOff, keywords: '오프' },
  { name: 'zap-off', label: '정전', group: '전원·전력', Cmp: ZapOff, keywords: '단전' },
  { name: 'fuel', label: '연료', group: '전원·전력', Cmp: Fuel, keywords: '에너지' },
  { name: 'flashlight', label: '조명', group: '전원·전력', Cmp: Flashlight, keywords: '발광 라이트' },
  { name: 'cable', label: '케이블', group: '전원·전력', Cmp: Cable, keywords: '배선 커넥터' },
  { name: 'ethernet-port', label: '포트', group: '전원·전력', Cmp: EthernetPort, keywords: '단자 커넥터' },

  // ── 통신 · 무선 ──────────────────────────────────────────────────
  { name: 'wifi', label: '무선', group: '통신·무선', Cmp: Wifi, keywords: '와이파이' },
  { name: 'bluetooth', label: '블루투스', group: '통신·무선', Cmp: Bluetooth },
  { name: 'nfc', label: 'NFC', group: '통신·무선', Cmp: Nfc },
  { name: 'antenna', label: '안테나', group: '통신·무선', Cmp: Antenna },
  { name: 'signal', label: '신호세기', group: '통신·무선', Cmp: Signal },
  { name: 'radio', label: '전파', group: '통신·무선', Cmp: Radio, keywords: 'rf' },
  { name: 'radio-tower', label: '기지국', group: '통신·무선', Cmp: RadioTower },
  { name: 'satellite', label: '위성', group: '통신·무선', Cmp: Satellite },
  { name: 'network', label: '네트워크', group: '통신·무선', Cmp: Network, keywords: '연결 망' },
  { name: 'share', label: '연계', group: '통신·무선', Cmp: Share2, keywords: '공유 분기' },
  { name: 'wifi-off', label: '무선끊김', group: '통신·무선', Cmp: WifiOff, keywords: '단절' },
  { name: 'wifi-high', label: '신호강함', group: '통신·무선', Cmp: WifiHigh, keywords: '양호' },
  { name: 'wifi-low', label: '신호약함', group: '통신·무선', Cmp: WifiLow, keywords: '미약' },
  { name: 'signal-high', label: '수신강', group: '통신·무선', Cmp: SignalHigh, keywords: '감도' },
  { name: 'signal-low', label: '수신약', group: '통신·무선', Cmp: SignalLow, keywords: '감도저하' },
  { name: 'signal-zero', label: '수신없음', group: '통신·무선', Cmp: SignalZero, keywords: '불통' },
  { name: 'bluetooth-connected', label: '페어링', group: '통신·무선', Cmp: BluetoothConnected, keywords: '연결됨' },
  { name: 'bluetooth-searching', label: '탐색중', group: '통신·무선', Cmp: BluetoothSearching, keywords: '검색' },
  { name: 'router', label: '공유기', group: '통신·무선', Cmp: Router, keywords: '라우터' },
  { name: 'satellite-dish', label: '수신안테나', group: '통신·무선', Cmp: SatelliteDish, keywords: '접시' },
  { name: 'radio-receiver', label: '수신기', group: '통신·무선', Cmp: RadioReceiver, keywords: '리시버' },
  { name: 'rss', label: '피드', group: '통신·무선', Cmp: Rss, keywords: '구독' },

  // ── 제품 · 기기 ──────────────────────────────────────────────────
  { name: 'smartphone', label: '스마트폰', group: '제품·기기', Cmp: Smartphone },
  { name: 'tablet', label: '태블릿', group: '제품·기기', Cmp: Tablet },
  { name: 'laptop', label: '노트북', group: '제품·기기', Cmp: Laptop },
  { name: 'monitor', label: '모니터', group: '제품·기기', Cmp: Monitor, keywords: '디스플레이 화면' },
  { name: 'tv', label: 'TV', group: '제품·기기', Cmp: Tv },
  { name: 'camera', label: '카메라', group: '제품·기기', Cmp: Camera, keywords: '이미지센서' },
  { name: 'mic', label: '마이크', group: '제품·기기', Cmp: Mic },
  { name: 'speaker', label: '스피커', group: '제품·기기', Cmp: Speaker },
  { name: 'headphones', label: '헤드폰', group: '제품·기기', Cmp: Headphones },
  { name: 'volume', label: '음량', group: '제품·기기', Cmp: Volume2, keywords: '소리' },
  { name: 'watch', label: '웨어러블', group: '제품·기기', Cmp: Watch, keywords: '시계 워치' },
  { name: 'keyboard', label: '키보드', group: '제품·기기', Cmp: Keyboard, keywords: '입력' },
  { name: 'mouse', label: '마우스', group: '제품·기기', Cmp: Mouse, keywords: '포인터' },
  { name: 'printer', label: '프린터', group: '제품·기기', Cmp: Printer, keywords: '출력' },
  { name: 'projector', label: '프로젝터', group: '제품·기기', Cmp: Projector, keywords: '영사' },
  { name: 'webcam', label: '웹캠', group: '제품·기기', Cmp: Webcam, keywords: '화상' },
  { name: 'joystick', label: '컨트롤러', group: '제품·기기', Cmp: Joystick, keywords: '조작' },
  { name: 'disc', label: '디스크', group: '제품·기기', Cmp: Disc, keywords: '미디어' },
  { name: 'monitor-smartphone', label: '멀티기기', group: '제품·기기', Cmp: MonitorSmartphone, keywords: '연동' },
  { name: 'smartphone-charging', label: '기기충전', group: '제품·기기', Cmp: SmartphoneCharging, keywords: '급전' },
  { name: 'smartphone-nfc', label: '근거리통신', group: '제품·기기', Cmp: SmartphoneNfc, keywords: '태그' },
  { name: 'tablet-smartphone', label: '모바일기기', group: '제품·기기', Cmp: TabletSmartphone, keywords: '단말' },
  { name: 'microwave', label: '가전', group: '제품·기기', Cmp: Microwave, keywords: '생활가전' },
  { name: 'refrigerator', label: '냉장', group: '제품·기기', Cmp: Refrigerator, keywords: '냉기기' },
  { name: 'washing-machine', label: '세탁', group: '제품·기기', Cmp: WashingMachine, keywords: '백색가전' },
  { name: 'air-vent', label: '공조', group: '제품·기기', Cmp: AirVent, keywords: '환기 흡배기' },
  { name: 'lamp', label: '조명기구', group: '제품·기기', Cmp: Lamp, keywords: '램프' },

  // ── 계측 · 시험 ──────────────────────────────────────────────────
  { name: 'gauge', label: '계측', group: '계측·시험', Cmp: Gauge, keywords: '게이지 측정' },
  { name: 'thermometer', label: '온도', group: '계측·시험', Cmp: Thermometer, keywords: '발열' },
  { name: 'fan', label: '방열', group: '계측·시험', Cmp: Fan, keywords: '냉각 팬' },
  { name: 'snowflake', label: '저온', group: '계측·시험', Cmp: Snowflake },
  { name: 'flame', label: '고온', group: '계측·시험', Cmp: Flame, keywords: '발화' },
  { name: 'droplet', label: '습도', group: '계측·시험', Cmp: Droplet, keywords: '방수 수분' },
  { name: 'wind', label: '기류', group: '계측·시험', Cmp: Wind },
  { name: 'waves', label: '진동', group: '계측·시험', Cmp: Waves, keywords: '파형' },
  { name: 'audio-waveform', label: '소음', group: '계측·시험', Cmp: AudioWaveform, keywords: '음향 파형' },
  { name: 'magnet', label: '자기', group: '계측·시험', Cmp: Magnet, keywords: 'emc 전자기' },
  { name: 'radiation', label: '방사', group: '계측·시험', Cmp: Radiation, keywords: 'emi 노이즈' },
  { name: 'ruler', label: '치수', group: '계측·시험', Cmp: Ruler },
  { name: 'scale', label: '중량', group: '계측·시험', Cmp: Scale, keywords: '무게 저울' },
  { name: 'timer', label: '수명', group: '계측·시험', Cmp: Timer, keywords: '내구 시간' },
  { name: 'radar', label: '탐지', group: '계측·시험', Cmp: Radar, keywords: '센서' },
  { name: 'scan', label: '검사', group: '계측·시험', Cmp: Scan },
  { name: 'fingerprint', label: '인식', group: '계측·시험', Cmp: Fingerprint, keywords: '지문 센서' },
  { name: 'microscope', label: '분석', group: '계측·시험', Cmp: Microscope, keywords: '현미경' },
  { name: 'flask', label: '실험', group: '계측·시험', Cmp: FlaskConical, keywords: '플라스크' },
  { name: 'test-tube', label: '시험', group: '계측·시험', Cmp: TestTube, keywords: '시험관' },
  { name: 'beaker', label: '시료', group: '계측·시험', Cmp: Beaker, keywords: '비커' },
  { name: 'syringe', label: '주입', group: '계측·시험', Cmp: Syringe, keywords: '시료주입' },
  { name: 'test-tubes', label: '다중시험', group: '계측·시험', Cmp: TestTubes, keywords: '병렬시험' },
  { name: 'flask-round', label: '용액', group: '계측·시험', Cmp: FlaskRound, keywords: '약품' },
  { name: 'thermometer-snowflake', label: '저온시험', group: '계측·시험', Cmp: ThermometerSnowflake, keywords: '냉시험' },
  { name: 'thermometer-sun', label: '고온시험', group: '계측·시험', Cmp: ThermometerSun, keywords: '열시험' },
  { name: 'scan-barcode', label: '바코드', group: '계측·시험', Cmp: ScanBarcode, keywords: '식별' },
  { name: 'scan-qr', label: 'QR', group: '계측·시험', Cmp: ScanQrCode, keywords: '코드' },
  { name: 'scan-line', label: '스캔', group: '계측·시험', Cmp: ScanLine, keywords: '판독' },
  { name: 'scan-eye', label: '외관검사', group: '계측·시험', Cmp: ScanEye, keywords: '육안' },
  { name: 'scan-search', label: '정밀검사', group: '계측·시험', Cmp: ScanSearch, keywords: '탐색검사' },
  { name: 'ruler-dimension', label: '치수선', group: '계측·시험', Cmp: RulerDimensionLine, keywords: '공차' },
  { name: 'gauge-circle', label: '계기', group: '계측·시험', Cmp: GaugeCircle, keywords: '다이얼' },
  { name: 'timer-reset', label: '재시험', group: '계측·시험', Cmp: TimerReset, keywords: '리셋' },
  { name: 'weight', label: '하중', group: '계측·시험', Cmp: Weight, keywords: '추 무게' },
  { name: 'orbit', label: '궤적', group: '계측·시험', Cmp: Orbit, keywords: '회전' },
  { name: 'aperture', label: '조리개', group: '계측·시험', Cmp: Aperture, keywords: '광학' },
  { name: 'focus', label: '초점', group: '계측·시험', Cmp: Focus, keywords: '포커스' },

  // ── 품질 · 판정 ──────────────────────────────────────────────────
  { name: 'check-circle', label: '합격', group: '품질·판정', Cmp: CircleCheck, keywords: '완료 확인 통과' },
  { name: 'badge-check', label: '인증', group: '품질·판정', Cmp: BadgeCheck, keywords: '검증 배지' },
  { name: 'alert-triangle', label: '경고', group: '품질·판정', Cmp: TriangleAlert, keywords: '주의 위험' },
  { name: 'alert-circle', label: '이상', group: '품질·판정', Cmp: AlertCircle },
  { name: 'bug', label: '결함', group: '품질·판정', Cmp: Bug, keywords: '불량 버그' },
  { name: 'shield', label: '안전', group: '품질·판정', Cmp: Shield },
  { name: 'shield-check', label: '검증완료', group: '품질·판정', Cmp: ShieldCheck },
  { name: 'shield-alert', label: '위험', group: '품질·판정', Cmp: ShieldAlert },
  { name: 'list-checks', label: '점검목록', group: '품질·판정', Cmp: ListChecks, keywords: '체크리스트' },
  { name: 'clipboard-check', label: '승인', group: '품질·판정', Cmp: ClipboardCheck },
  { name: 'file-check', label: '검토완료', group: '품질·판정', Cmp: FileCheck },
  { name: 'info', label: '정보', group: '품질·판정', Cmp: Info },
  { name: 'eye', label: '관찰', group: '품질·판정', Cmp: Eye, keywords: '모니터링' },
  { name: 'check-check', label: '이중확인', group: '품질·판정', Cmp: CheckCheck, keywords: '재확인' },
  { name: 'octagon-alert', label: '중대이슈', group: '품질·판정', Cmp: OctagonAlert, keywords: '치명' },
  { name: 'ban', label: '금지', group: '품질·판정', Cmp: Ban, keywords: '불가' },
  { name: 'circle-slash', label: '해당없음', group: '품질·판정', Cmp: CircleSlash, keywords: '제외' },
  { name: 'shield-x', label: '취약', group: '품질·판정', Cmp: ShieldX, keywords: '미흡' },
  { name: 'shield-off', label: '보호해제', group: '품질·판정', Cmp: ShieldOff, keywords: '무방비' },
  { name: 'thumbs-up', label: '적합', group: '품질·판정', Cmp: ThumbsUp, keywords: '양호 승인 찬성' },
  { name: 'thumbs-down', label: '반려', group: '품질·판정', Cmp: ThumbsDown, keywords: '부적합' },
  { name: 'trophy', label: '최우수', group: '품질·판정', Cmp: Trophy, keywords: '수상' },
  { name: 'medal', label: '등급', group: '품질·판정', Cmp: Medal, keywords: '메달' },
  { name: 'star', label: '중요', group: '품질·판정', Cmp: Star, keywords: '핵심' },
  { name: 'bookmark-check', label: '확정', group: '품질·판정', Cmp: BookmarkCheck, keywords: '북마크' },
  { name: 'list-todo', label: '할일', group: '품질·판정', Cmp: ListTodo, keywords: '조치목록' },
  { name: 'triangle-dashed', label: '잠정', group: '품질·판정', Cmp: TriangleDashed, keywords: '미확정' },
  { name: 'circle-help', label: '미정', group: '품질·판정', Cmp: CircleHelp, keywords: '확인필요' },
  { name: 'circle-dot', label: '진행중', group: '품질·판정', Cmp: CircleDot, keywords: '상태' },

  // ── 지표 · 성과 ──────────────────────────────────────────────────
  { name: 'chart-column', label: '막대그래프', group: '지표·성과', Cmp: ChartColumn, keywords: '통계' },
  { name: 'chart-line', label: '추세', group: '지표·성과', Cmp: ChartLine, keywords: '선그래프' },
  { name: 'chart-pie', label: '비율', group: '지표·성과', Cmp: ChartPie, keywords: '원그래프' },
  { name: 'trending-up', label: '상승', group: '지표·성과', Cmp: TrendingUp, keywords: '증가 개선' },
  { name: 'trending-down', label: '하락', group: '지표·성과', Cmp: TrendingDown, keywords: '감소' },
  { name: 'activity', label: '변동', group: '지표·성과', Cmp: Activity },
  { name: 'target', label: '목표', group: '지표·성과', Cmp: Target },
  { name: 'flag', label: '이정표', group: '지표·성과', Cmp: Flag, keywords: '마일스톤' },
  { name: 'award', label: '성과', group: '지표·성과', Cmp: Award, keywords: '수상' },
  { name: 'coins', label: '비용', group: '지표·성과', Cmp: Coins, keywords: '원가 돈' },
  { name: 'chart-area', label: '누적추이', group: '지표·성과', Cmp: ChartArea, keywords: '영역' },
  { name: 'chart-bar', label: '가로막대', group: '지표·성과', Cmp: ChartBar, keywords: '비교' },
  { name: 'chart-scatter', label: '산포', group: '지표·성과', Cmp: ChartScatter, keywords: '상관 분포' },
  { name: 'chart-gantt', label: '일정표', group: '지표·성과', Cmp: ChartGantt, keywords: '간트' },
  { name: 'chart-candlestick', label: '변동폭', group: '지표·성과', Cmp: ChartCandlestick, keywords: '범위' },
  { name: 'chart-network', label: '관계도', group: '지표·성과', Cmp: ChartNetwork, keywords: '연결분석' },
  { name: 'chart-spline', label: '평활추세', group: '지표·성과', Cmp: ChartSpline, keywords: '곡선' },
  { name: 'percent', label: '달성률', group: '지표·성과', Cmp: Percent, keywords: '퍼센트 비율' },
  { name: 'sigma', label: '합계', group: '지표·성과', Cmp: Sigma, keywords: '시그마 통계' },
  { name: 'calculator', label: '산출', group: '지표·성과', Cmp: Calculator, keywords: '계산' },
  { name: 'layout-dashboard', label: '대시보드', group: '지표·성과', Cmp: LayoutDashboard, keywords: '현황판' },
  { name: 'table', label: '표', group: '지표·성과', Cmp: Table, keywords: '집계표' },
  { name: 'kanban', label: '칸반', group: '지표·성과', Cmp: Kanban, keywords: '진행판' },
  { name: 'list-ordered', label: '순위', group: '지표·성과', Cmp: ListOrdered, keywords: '우선순위' },
  { name: 'trending-up-down', label: '등락', group: '지표·성과', Cmp: TrendingUpDown, keywords: '변동' },
  { name: 'banknote', label: '예산', group: '지표·성과', Cmp: Banknote, keywords: '금액' },
  { name: 'wallet', label: '재원', group: '지표·성과', Cmp: Wallet, keywords: '지갑' },
  { name: 'receipt', label: '정산', group: '지표·성과', Cmp: Receipt, keywords: '비용내역' },

  // ── 생산 · 공급 ──────────────────────────────────────────────────
  { name: 'factory', label: '생산', group: '생산·공급', Cmp: Factory, keywords: '공장 양산' },
  { name: 'warehouse', label: '창고', group: '생산·공급', Cmp: Warehouse, keywords: '재고' },
  { name: 'container', label: '물류', group: '생산·공급', Cmp: Container },
  { name: 'truck', label: '납품', group: '생산·공급', Cmp: Truck, keywords: '배송 운송' },
  { name: 'package', label: '포장', group: '생산·공급', Cmp: Package, keywords: '패키지' },
  { name: 'boxes', label: '자재', group: '생산·공급', Cmp: Boxes },
  { name: 'handshake', label: '협력사', group: '생산·공급', Cmp: Handshake, keywords: '공급사 계약' },
  { name: 'wrench', label: '정비', group: '생산·공급', Cmp: Wrench, keywords: '수리 조치' },
  { name: 'hammer', label: '개조', group: '생산·공급', Cmp: Hammer },
  { name: 'cog', label: '공정', group: '생산·공급', Cmp: Cog, keywords: '설비 기어' },
  { name: 'settings', label: '설정', group: '생산·공급', Cmp: Settings, keywords: '조건' },
  { name: 'recycle', label: '재활용', group: '생산·공급', Cmp: Recycle, keywords: '친환경' },
  { name: 'leaf', label: '환경', group: '생산·공급', Cmp: Leaf },
  { name: 'forklift', label: '지게차', group: '생산·공급', Cmp: Forklift, keywords: '운반' },
  { name: 'hard-hat', label: '보호구', group: '생산·공급', Cmp: HardHat, keywords: '안전모 안전' },
  { name: 'construction', label: '설치', group: '생산·공급', Cmp: Construction, keywords: '시공' },
  { name: 'drill', label: '가공', group: '생산·공급', Cmp: Drill, keywords: '드릴' },
  { name: 'anvil', label: '성형', group: '생산·공급', Cmp: Anvil, keywords: '금형' },
  { name: 'archive', label: '보관', group: '생산·공급', Cmp: Archive, keywords: '아카이브' },
  { name: 'package-check', label: '입고검사', group: '생산·공급', Cmp: PackageCheck, keywords: '수입검사' },
  { name: 'package-open', label: '개봉', group: '생산·공급', Cmp: PackageOpen, keywords: '언박싱' },
  { name: 'package-search', label: '추적', group: '생산·공급', Cmp: PackageSearch, keywords: '조회' },
  { name: 'truck-electric', label: '친환경물류', group: '생산·공급', Cmp: TruckElectric, keywords: '전동' },
  { name: 'trash', label: '폐기', group: '생산·공급', Cmp: Trash2, keywords: '스크랩' },
  { name: 'store', label: '판매', group: '생산·공급', Cmp: Store, keywords: '매장' },
  { name: 'shopping-cart', label: '발주', group: '생산·공급', Cmp: ShoppingCart, keywords: '구매' },
  { name: 'barcode', label: '식별코드', group: '생산·공급', Cmp: Barcode, keywords: '바코드' },

  // ── 데이터 · 소프트웨어 ──────────────────────────────────────────
  { name: 'database', label: '데이터', group: '데이터·SW', Cmp: Database },
  { name: 'server', label: '서버', group: '데이터·SW', Cmp: Server },
  { name: 'hard-drive', label: '저장장치', group: '데이터·SW', Cmp: HardDrive },
  { name: 'cloud', label: '클라우드', group: '데이터·SW', Cmp: Cloud },
  { name: 'code', label: '코드', group: '데이터·SW', Cmp: Code, keywords: '펌웨어 소프트웨어' },
  { name: 'terminal', label: '실행', group: '데이터·SW', Cmp: Terminal, keywords: '명령' },
  { name: 'layers', label: '계층', group: '데이터·SW', Cmp: Layers, keywords: '구조 스택' },
  { name: 'filter', label: '필터', group: '데이터·SW', Cmp: Filter, keywords: '선별' },
  { name: 'search', label: '조사', group: '데이터·SW', Cmp: Search, keywords: '검색 탐색' },
  { name: 'link', label: '연결', group: '데이터·SW', Cmp: Link },
  { name: 'lock', label: '보안', group: '데이터·SW', Cmp: Lock, keywords: '잠금' },
  { name: 'git-commit', label: '변경점', group: '데이터·SW', Cmp: GitCommitHorizontal, keywords: '커밋' },
  { name: 'git-merge', label: '병합', group: '데이터·SW', Cmp: GitMerge, keywords: '머지' },
  { name: 'git-pull-request', label: '반영요청', group: '데이터·SW', Cmp: GitPullRequest, keywords: 'PR' },
  { name: 'file-code', label: '소스', group: '데이터·SW', Cmp: FileCode, keywords: '코드파일' },
  { name: 'database-zap', label: '실시간', group: '데이터·SW', Cmp: DatabaseZap, keywords: '즉시처리' },
  { name: 'server-cog', label: '서버설정', group: '데이터·SW', Cmp: ServerCog, keywords: '인프라' },
  { name: 'cloud-upload', label: '업로드', group: '데이터·SW', Cmp: CloudUpload, keywords: '전송' },
  { name: 'cloud-download', label: '다운로드', group: '데이터·SW', Cmp: CloudDownload, keywords: '수신' },
  { name: 'folder-git', label: '저장소', group: '데이터·SW', Cmp: FolderGit, keywords: '리포지토리' },
  { name: 'bug-play', label: '재현', group: '데이터·SW', Cmp: BugPlay, keywords: '디버깅' },
  { name: 'braces', label: '파라미터', group: '데이터·SW', Cmp: Braces, keywords: '설정값' },

  // ── 일정 · 조직 ──────────────────────────────────────────────────
  { name: 'workflow', label: '흐름', group: '일정·조직', Cmp: Workflow, keywords: '프로세스' },
  { name: 'git-branch', label: '분기', group: '일정·조직', Cmp: GitBranch, keywords: '버전' },
  { name: 'milestone', label: '단계', group: '일정·조직', Cmp: Milestone, keywords: '게이트' },
  { name: 'clock', label: '시간', group: '일정·조직', Cmp: Clock },
  { name: 'calendar', label: '일정', group: '일정·조직', Cmp: Calendar },
  { name: 'calendar-clock', label: '기한', group: '일정·조직', Cmp: CalendarClock, keywords: '마감' },
  { name: 'history', label: '이력', group: '일정·조직', Cmp: History, keywords: '과거' },
  { name: 'refresh', label: '갱신', group: '일정·조직', Cmp: RefreshCw, keywords: '반복 재시험' },
  { name: 'users', label: '조직', group: '일정·조직', Cmp: Users, keywords: '팀 사람' },
  { name: 'user', label: '담당자', group: '일정·조직', Cmp: User },
  { name: 'building', label: '부서', group: '일정·조직', Cmp: Building2, keywords: '사업장' },
  { name: 'user-check', label: '승인자', group: '일정·조직', Cmp: UserCheck, keywords: '확인자' },
  { name: 'user-plus', label: '인원충원', group: '일정·조직', Cmp: UserPlus, keywords: '추가' },
  { name: 'users-round', label: '협업', group: '일정·조직', Cmp: UsersRound, keywords: '팀' },
  { name: 'briefcase', label: '과제', group: '일정·조직', Cmp: Briefcase, keywords: '업무' },
  { name: 'presentation', label: '발표', group: '일정·조직', Cmp: Presentation, keywords: '보고' },
  { name: 'mail', label: '메일', group: '일정·조직', Cmp: Mail, keywords: '통보' },
  { name: 'bell', label: '알림', group: '일정·조직', Cmp: Bell, keywords: '경보' },
  { name: 'map-pin', label: '장소', group: '일정·조직', Cmp: MapPin, keywords: '거점' },
  { name: 'globe', label: '해외', group: '일정·조직', Cmp: Globe, keywords: '글로벌' },
  { name: 'contact', label: '연락처', group: '일정·조직', Cmp: Contact, keywords: '담당' },
  { name: 'id-card', label: '신원', group: '일정·조직', Cmp: IdCard, keywords: '사번' },
  { name: 'landmark', label: '기관', group: '일정·조직', Cmp: Landmark, keywords: '대외' },

  // ── 문서 · 기타 ──────────────────────────────────────────────────
  { name: 'file-text', label: '문서', group: '문서·기타', Cmp: FileText, keywords: '보고서' },
  { name: 'clipboard-list', label: '목록', group: '문서·기타', Cmp: ClipboardList },
  { name: 'book', label: '규격', group: '문서·기타', Cmp: Book, keywords: '표준 매뉴얼' },
  { name: 'lightbulb', label: '아이디어', group: '문서·기타', Cmp: Lightbulb, keywords: '제안 개선' },
  { name: 'sparkles', label: '신규', group: '문서·기타', Cmp: Sparkles, keywords: 'ai 특징' },
  { name: 'book-open', label: '열람', group: '문서·기타', Cmp: BookOpen, keywords: '참고자료' },
  { name: 'file-search', label: '문서검색', group: '문서·기타', Cmp: FileSearch, keywords: '조회' },
  { name: 'file-plus', label: '신규문서', group: '문서·기타', Cmp: FilePlus, keywords: '작성' },
  { name: 'files', label: '문서묶음', group: '문서·기타', Cmp: Files, keywords: '일괄' },
  { name: 'folder', label: '폴더', group: '문서·기타', Cmp: Folder, keywords: '분류' },
  { name: 'folder-open', label: '열린폴더', group: '문서·기타', Cmp: FolderOpen, keywords: '탐색' },
  { name: 'paperclip', label: '첨부', group: '문서·기타', Cmp: Paperclip, keywords: '클립' },
  { name: 'pin', label: '고정', group: '문서·기타', Cmp: Pin, keywords: '핀' },
  { name: 'quote', label: '인용', group: '문서·기타', Cmp: Quote, keywords: '발췌' },
  { name: 'pen-tool', label: '설계', group: '문서·기타', Cmp: PenTool, keywords: '작도' },
  { name: 'stamp', label: '결재', group: '문서·기타', Cmp: Stamp, keywords: '날인' },
  { name: 'languages', label: '번역', group: '문서·기타', Cmp: Languages, keywords: '다국어' },
  { name: 'table-of-contents', label: '목차', group: '문서·기타', Cmp: TableOfContents, keywords: '차례' },
  { name: 'notebook-pen', label: '기록', group: '문서·기타', Cmp: NotebookPen, keywords: '메모' },
  { name: 'sticky-note', label: '메모지', group: '문서·기타', Cmp: StickyNote, keywords: '노트' },
  { name: 'highlighter', label: '강조', group: '문서·기타', Cmp: Highlighter, keywords: '형광' },
  { name: 'signature', label: '서명', group: '문서·기타', Cmp: Signature, keywords: '사인' },
  { name: 'scroll-text', label: '규정', group: '문서·기타', Cmp: ScrollText, keywords: '조문' },
]

/** 저장 이름 → 컴포넌트. */
export const CARD_ICONS = Object.fromEntries(
  CARD_ICON_DEFS.map((d) => [d.name, d.Cmp]),
)

export const CARD_ICON_NAMES = CARD_ICON_DEFS.map((d) => d.name)

/** 이름 → 컴포넌트. 허용셋 밖이면 null(렌더 생략 — 깨진 아이콘 대신 무시). */
export function cardIconComponent(name) {
  return (typeof name === 'string' && CARD_ICONS[name]) || null
}

/** 이름 → 한글 라벨(피커·툴팁용). 없으면 이름 그대로. */
export function cardIconLabel(name) {
  return CARD_ICON_DEFS.find((d) => d.name === name)?.label ?? name ?? ''
}

/**
 * 검색 — 한글 라벨 · 저장 이름 · 보조 키워드 · 그룹명을 모두 훑는다.
 * 빈 질의면 전체. 한글로 찾는 게 기본이라 라벨을 먼저 본다.
 */
export function searchCardIcons(query) {
  const q = (query ?? '').trim().toLowerCase()
  if (!q) return CARD_ICON_DEFS
  return CARD_ICON_DEFS.filter((d) =>
    d.label.toLowerCase().includes(q) ||
    d.name.includes(q) ||
    (d.keywords ?? '').includes(q) ||
    d.group.toLowerCase().includes(q),
  )
}
