"""init phase 1 schema

Revision ID: 19d4b398b211
Revises: 
Create Date: 2026-05-05 17:31:05.195193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19d4b398b211'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workspaces',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('parent_slug', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=False),
    sa.Column('virtual', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_slug'], ['workspaces.slug'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('templates',
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner_workspace_slug', sa.String(length=64), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_workspace_slug'], ['workspaces.slug'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('template_id', 'version', name='pk_templates')
    )
    op.create_index('ix_templates_owner_workspace', 'templates', ['owner_workspace_slug'], unique=False)
    op.create_index('ix_templates_template_id', 'templates', ['template_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_slug', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_slug'], ['workspaces.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workspace_slug', name='uq_user_workspace')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_slug'), 'workspace_members', ['workspace_slug'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_slug', sa.String(length=64), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_review', 'approved', 'archived', name='report_status_enum'), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id', 'template_version'], ['templates.template_id', 'templates.version'], name='fk_reports_template_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_slug'], ['workspaces.slug'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_owner', 'reports', ['owner_user_id'], unique=False)
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False)
    op.create_index('ix_reports_template', 'reports', ['template_id', 'template_version'], unique=False)
    op.create_index('ix_reports_workspace', 'reports', ['workspace_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_workspace', table_name='reports')
    op.drop_index('ix_reports_template', table_name='reports')
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index('ix_reports_owner', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_workspace_members_workspace_slug'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index('ix_templates_template_id', table_name='templates')
    op.drop_index('ix_templates_owner_workspace', table_name='templates')
    op.drop_table('templates')
    op.drop_table('workspaces')
    op.drop_table('users')
    # ### end Alembic commands ###
