"""reports.layout_overrides

Revision ID: 1eb745bfd049
Revises: f6c168512385
Create Date: 2026-05-06 20:56:37.028570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eb745bfd049'
down_revision: Union[str, None] = 'f6c168512385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('layout_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'layout_overrides')
    # ### end Alembic commands ###
