"""phase 2 report activities

Revision ID: f943a72fe3ad
Revises: cf2bcf8d19e8
Create Date: 2026-05-25 09:03:12.722422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f943a72fe3ad'
down_revision: Union[str, None] = 'cf2bcf8d19e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('created', 'edited', 'comment_added', 'comment_replied', 'thread_resolved', 'thread_reopened', 'phase_to_reviewing', 'phase_to_finalized', 'phase_to_drafting', 'mounted', 'unmounted', 'mount_folder_changed', 'folder_changed', 'locked', 'unlocked', 'lock_force_unset', name='report_activity_type_enum'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_activities_actor', 'report_activities', ['actor_user_id'], unique=False)
    op.create_index('ix_report_activities_report_created', 'report_activities', ['report_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_report_activities_report_created', table_name='report_activities')
    op.drop_index('ix_report_activities_actor', table_name='report_activities')
    op.drop_table('report_activities')
    op.execute("DROP TYPE report_activity_type_enum")
